# Database
spring.datasource.url=jdbc:mysql://localhost:3306/ratelimiter_db
spring.datasource.username=root
spring.datasource.password=Kesava@2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - auto creates tables from @Entity classes on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Server
server.port=8080

# Rate limit settings (read in service using @Value)
app.rate-limit.max-requests-per-minute=100
app.rate-limit.window-size-seconds=60